  version: '3.9'

  services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      depends_on:
        - db
    
    db:
      image: postgres:14
      environment:
        POSTGRES_DB: shaman_db  
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1998
      volumes:
        - pgdata:/var/lib/postgresql/data

  volumes:
    pgdata:
