# Generated by Django 5.2.3 on 2025-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_signuptempsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptempsession',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='signuptempsession',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
